name: Build and Deploy Frontend

on:
  push:
    branches:
      - main  # или твоя ветка

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # или версия, которую ты используешь

    - name: Install dependencies
      run: npm ci

    - name: Build Next.js app
      run: npm run build

    - name: Deploy to server via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        source: |
          .next
          node_modules
          public
          package.json
          next.config.js
        target: /root/apps/frontend/repo/

    - name: Restart pm2 on server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd /root/apps/frontend/repo
          pm2 restart frontend || pm2 start npm --name frontend -- run start
