name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main  # или твоя ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Upload source files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: |
          pages
          public
          package.json
          package-lock.json # если есть
          next.config.js
          # другие нужные файлы/папки
        target: /root/apps/frontend

    - name: Build and start on server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /root/apps/frontend
          npm install
          npm run build
          pm2 restart frontend || pm2 start npm --name frontend -- run start
